name: bts
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - torchvision
  - matplotlib
  - numpy
  - opencv
  - moviepy
  - seaborn
  - mediapy
  - notebook
  - scipy
  - scikit-image
  - pip
  - pip:
      - tensorflow-datasets
      - pytorch-ignite
      - hydra-core
      - omegaconf
      - h5py
      - lpips
      - dotmap
      - dotdict
      - pytorch-msssim