name: bts
channels:
  - pytorch
  - nvidia
dependencies:
  - python
  - pytorch=1.13.1
  - torchvision==0.14.1
  - pytorch-cuda=11.6
  - pip
  - pip:
      - tensorflow-datasets
      - pytorch-ignite
      - hydra-core
      - omegaconf
      - h5py
      - lpips
      - dotmap
      - dotdict
      - pytorch-msssim
      - plyfile
      - tensorflow # for tensorboard (but it seems to be much faster with tensorflow)
      - opencv-python
      - matplotlib
      - moviepy
      - mediapy
      - scipy
      - scikit-image
      - notebook