defaults:
    - default
    - data: kitti_raw
    - _self_

name: "kitti_raw"
model: "bts"
output_path: "out/kitti_raw"

num_epochs: 50
batch_size: 16

save_best:
    metric: abs_rel
    sign: -1

data:
    data_fc: 2
    image_size: [192, 640]
    color_aug: true
    data_stereo: true

model_conf:
    arch: "BTSNet"
    use_code: true
    prediction_mode: default

    code:
        num_freqs: 6
        freq_factor: 1.5
        include_input: true

    encoder:
        type: "monodepth2"
        freeze: false
        pretrained: true
        resnet_layers: 50
        num_ch_dec: [32,32,64,128,256]
        d_out: 64

    mlp_coarse:
        type : "resnet"
        n_blocks : 0
        d_hidden : 64

    mlp_fine:
        type : "empty"
        n_blocks : 1
        d_hidden : 128

    z_near: 3
    z_far: 80
    inv_z: true

    n_frames_encoder: 1
    n_frames_render: 2
    frame_sample_mode: default

    sample_mode: patch
    patch_size: 8
    ray_batch_size: 2048

    flip_augmentation: true

    learn_empty: false
    code_mode: z

loss:
    criterion: "l1+ssim"
    invalid_policy: weight_guided
    lambda_edge_aware_smoothness: 0.001

scheduler:
    type: step
    step_size: 120000
    gamma: 0.1

renderer:
    n_coarse : 64
    n_fine : 0
    n_fine_depth : 0
    depth_std : 1.0
    sched : []
    white_bkgd : false
    lindisp: true
    hard_alpha_cap: true
